language: ruby
rvm:
  - 2.2.1
  - 2.1.0
  - 1.9.3
  #- jruby-1.7.19
  #- 1.8.7

script:
   #- "bundle exec rake tests"
   - "bundle exec rake tests[chrome]"

before_install:
  #Installing ChromeDriver
   - wget http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip
   - apt-get install unzip
   - wget -N http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip -P ~/Downloads
   - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
   - chmod +x ~/Downloads/chromedriver
   - mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver
   - ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
   - ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
  ##
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3
   - bundle install
   - rackup &
   - sleep 5

branches:
  only:
    - testing
