language: ruby
rvm:
  - 1.9.3

script:
   "bundle exec rake tests"

before_install:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3
   - bundle install
   - bundle exec rake rackup &
   - sleep 5

branches:
  only:
    - testing
