language: ruby
rvm:
  - 2.2.1
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - 1.8.7

script:
   "bundle exec rake tests"

before_install:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3
   - bundle install
   - bundle exec rake rackup &
   - sleep 5

branches:
  only:
    - testing
